### ISSUE TITLE
Spotify login through our app

### ISSUE THREAD

**Issue by masonmcelvain** [masonmcelvain/geomusic#22]
# Frontend
Onpress user is prompted to authorize account use and access in in-app browser. Redirect uri is sent to the backend and get token for further API calls.

Actual Time: 3 hr - for the JS portion, after the many hours spent with the spotipy library

# Backend
Store user uri with name and email. Put any relevant info in DB
You could try to test the login without the frontend

Mid sprint deadline: Sunday night, May 16.

Estimate 3 hours

**Comment by nbehmane** [comment]
Successfully authenticated Spotify through the app.
