### ISSUE TITLE
Add new routes

### ISSUE THREAD

**Issue by nbehmane** [masonmcelvain/geomusic#47]
* Endpoint to get all songs from a playlist
* A 'search song' route
* a way to get a few playlists recently listened to by the user (up to a specified limit), and a way to get a few playlists nearby the user (up to a specified limit)

**Comment by nbehmane** [comment]
Made an endpoint to get all songs from a playlist given a playlist id:
`/playlist/tracks/get/<playlist_id>`

**Comment by kylene-phillips** [comment]
Routes are working with the frontend. Thanks nima!
